CREATE TABLE EMPLOYEE (
    EMP_ID          NUMBER(10) PRIMARY KEY,
    FIRST_NAME      VARCHAR2(100) NOT NULL,
    LAST_NAME       VARCHAR2(100) NOT NULL,
    EMAIL           VARCHAR2(255) UNIQUE,
    PHONE_NUMBER    VARCHAR2(20),
    HIRE_DATE       DATE NOT NULL,
    JOB_TITLE       VARCHAR2(100),
    SALARY          NUMBER(10,2),
    DEPARTMENT_ID   NUMBER(10),
    CREATED_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE    TIMESTAMP
);