name: DB Deployment

on:
  push:
    branches:
      - develop
      - qa
      - main

jobs:

  deploy-db:

    runs-on: self-hosted

    environment: PROD

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:

      # =====================================================
      # Checkout Repository
      # =====================================================

      - name: Checkout Repository
        uses: actions/checkout@v4

      # =====================================================
      # Debug Environment Selection
      # =====================================================

      - name: Debug Environment Selection
        shell: powershell
        run: |

          Write-Host "Branch Name = ${{ github.ref_name }}"

          if ("${{ github.ref_name }}" -eq "develop") {
            Write-Host "Matched DEV environment"
          }
          elseif ("${{ github.ref_name }}" -eq "qa") {
            Write-Host "Matched QA environment"
          }
          elseif ("${{ github.ref_name }}" -eq "main") {
            Write-Host "Matched PROD environment"
          }
          else {
            Write-Host "No branch match found"
          }

          if ($env:DB_URL) {
            Write-Host "DB_URL exists"
          }
          else {
            Write-Host "DB_URL missing"
            exit 1
          }

      # =====================================================
      # Generate release.sql From manifest.yml
      # =====================================================

      - name: Generate release.sql
        shell: powershell
        run: |

          $manifestPath = "database/app_schema/deployment/manifest.yml"
          $releaseFile = "release.sql"

          if (Test-Path $releaseFile) {
            Remove-Item $releaseFile
          }

          New-Item `
            -Path $releaseFile `
            -ItemType File `
            -Force

          $lines = Get-Content $manifestPath

          foreach ($line in $lines) {

            if ($line -match "^\s*-\s*(.*)") {

              $file = $matches[1].Trim()

              Add-Content `
                -Path $releaseFile `
                -Value "@@database/app_schema/$file"
            }
          }

          Write-Host "===== GENERATED release.sql ====="

          Get-Content $releaseFile

      # =====================================================
      # Execute Deployment
      # =====================================================

      - name: Execute release.sql
        shell: powershell
        run: |

                @"
                CONNECT $env:DB_USER/$env:DB_PASSWORD@$env:DB_CONNECT

                @release.sql

                EXIT;
                "@ | Out-File run_release.sql -Encoding ascii

                Write-Host "===== run_release.sql ====="

                Get-Content run_release.sql

                sqlplus /nolog @run_release.sql

      # =====================================================
      # Compile Invalid Objects
      # =====================================================

    #   - name: Compile Invalid Objects
    #     shell: powershell
    #     run: |

    #       @"
    #       BEGIN
    #         DBMS_UTILITY.compile_schema(
    #           schema => 'APP_SCHEMA'
    #         );
    #       END;
    #       /
    #       EXIT;
    #       "@ | Out-File compile.sql

    #         sqlplus `
    #         "$env:DB_USER/$env:DB_PASSWORD@$env:DB_CONNECT" `
    #         "@/compile.sql"

    #   # =====================================================
    #   # Validate Invalid Objects
    #   # =====================================================

    #   - name: Validate Invalid Objects
    #     shell: powershell
    #     run: |

    #       @"
    #       SET HEADING OFF;
    #       SET FEEDBACK OFF;

    #       SELECT object_name || ' - ' || object_type
    #       FROM user_objects
    #       WHERE status = 'INVALID';

    #       EXIT;
    #       "@ | Out-File validate_invalid.sql

    #       sqlplus `
    #         -s `
    #         $env:DB_USER/$env:DB_PASSWORD@$env:DB_URL `
    #         @validate_invalid.sql