name: DB2 Deployment

on:
  push:
    branches:
      - main

jobs:

  deploy-prod:

    runs-on: self-hosted

    environment: PROD

    env:
      DB_CONNECT: ${{ secrets.DB_CONNECT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:

      # =====================================================
      # Checkout Repository
      # =====================================================

      - name: Checkout Repository
        uses: actions/checkout@v4

      # =====================================================
      # Debug Environment
      # =====================================================

      - name: Debug Environment
        shell: powershell
        run: |

          Write-Host "Branch Name = ${{ github.ref_name }}"
          Write-Host "Deploying To PROD"

          if ($env:DB_CONNECT) {
            Write-Host "DB_CONNECT exists"
          }
         