name: DB Deployment

on:
  push:
    branches:
      - develop
      - qa
      - main



jobs:

  deploy-db:

    runs-on: self-hosted

    
    environment: PROD

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Environment Selection
        shell: powershell
        run: |

            Write-Host "Branch Name = ${{ github.ref_name }}"

            if ("${{ github.ref_name }}" -eq "develop") {
              Write-Host "Matched DEV environment"
            }
            elseif ("${{ github.ref_name }}" -eq "qa") {
              Write-Host "Matched QA environment"
            }
            elseif ("${{ github.ref_name }}" -eq "main") {
              Write-Host "Matched PROD environment"
            }
            else {
              Write-Host "No branch match found"
            }

            if ($env:DB_URL) {
              Write-Host "DB_URL exists"
            }
            else {
              Write-Host "DB_URL missing"
            }

            if ($env:DB_USER) {
              Write-Host "DB_USER exists"
            }
            else {
              Write-Host "DB_USER missing"
            }

            if ($env:DB_PASSWORD) {
              Write-Host "DB_PASSWORD exists"
            }
            else {
              Write-Host "DB_PASSWORD missing"
            }
      # - name: Set Environment Variables
      #   shell: powershell
      #   run: |

      #     if ("${{ github.ref_name }}" -eq "develop") {
      #       echo "DB_URL=${{ secrets.DEV_DB_URL }}" >> $env:GITHUB_ENV
      #       echo "DB_USER=${{ secrets.DEV_DB_USER }}" >> $env:GITHUB_ENV
      #       echo "DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}" >> $env:GITHUB_ENV
      #     }

      #     elseif ("${{ github.ref_name }}" -eq "qa") {
      #       echo "DB_URL=${{ secrets.QA_DB_URL }}" >> $env:GITHUB_ENV
      #       echo "DB_USER=${{ secrets.QA_DB_USER }}" >> $env:GITHUB_ENV
      #       echo "DB_PASSWORD=${{ secrets.QA_DB_PASSWORD }}" >> $env:GITHUB_ENV
      #     }

      #     elseif ("${{ github.ref_name }}" -eq "main") {
      #       echo "DB_URL=${{ secrets.PROD_DB_URL }}" >> $env:GITHUB_ENV
      #       echo "DB_USER=${{ secrets.PROD_DB_USER }}" >> $env:GITHUB_ENV
      #       echo "DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}" >> $env:GITHUB_ENV
      #     }

      - name: Flyway Validate
        shell: powershell
        run: |

          docker run --rm `
            -v "${{ github.workspace }}\database\migrations:/flyway/sql" `
            flyway/flyway `
            -url="$env:DB_URL" `
            -user="$env:DB_USER" `
            -password="$env:DB_PASSWORD" `
            validate

      - name: Flyway Info
        shell: powershell
        run: |

          docker run --rm `
            -v "${{ github.workspace }}\database\migrations:/flyway/sql" `
            flyway/flyway `
            -url="$env:DB_URL" `
            -user="$env:DB_USER" `
            -password="$env:DB_PASSWORD" `
            info


      - name: Debug Repeatable Folder
        shell: powershell
        run: |
          Write-Host "=== MIGRATIONS ==="
          dir "${{ github.workspace }}\database\migrations"

          Write-Host "=== REPEATABLE ==="
          dir "${{ github.workspace }}\database\repeatable"

   
          
      - name: Flyway Migrate
        shell: powershell
        run: |

          docker run --rm `
            -v "${{ github.workspace }}\database\migrations:/flyway/sql" `
            -v "${{ github.workspace }}\database\repeatable:/flyway/repeatable" `
            flyway/flyway `
            -url="$env:DB_URL" `
            -user="$env:DB_USER" `
            -password="$env:DB_PASSWORD" `
            -locations="filesystem:/flyway/sql,filesystem:/flyway/repeatable" `
            migrate