name: Flyway Repair

on:
  workflow_dispatch:

jobs:

  repair-db:

    runs-on: self-hosted

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Flyway Repair
        shell: powershell
        run: |

          docker run --rm `
            -v "${{ github.workspace }}\database\migrations:/flyway/sql" `
            flyway/flyway `
            -url="$env:DB_URL" `
            -user="$env:DB_USER" `
            -password="$env:DB_PASSWORD" `
            repair